<?php
$startDate = isset($_POST['start_date']) ? $_POST['start_date'] : '';
$endDate = isset($_POST['end_date']) ? $_POST['end_date'] : '';
?>
<div>
    <form method="GET" action="<?= $block->getFormUrl()?>">
        <label for="start_date">Start Date:</label>
        <input type="date" id="start_date" name="start_date" value="<?php echo $startDate; ?>">
        
        <label for="end_date">End Date:</label>
        <input type="date" id="end_date" name="end_date" value="<?php echo $endDate; ?>">
        
        <select name="affiliate_id" id="affiliate_id">
            <?php foreach ($block->getAffiliateIds() as $id):?>
                <option value="<?= $id['affiliate_id']?>"><?= $id['affiliate_id']?></option>
            <?php endforeach;?>
  
        </select>

        <input type="hidden" value="<?= $block->getFormKey()?>"  name="form_key">
        <input type="submit" value="Show Report">
    </form>
</div>
<style>
    /* Tablo stilleri */
    #affiliate_orders_table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    #affiliate_orders_table th,
    #affiliate_orders_table td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    #affiliate_orders_table th {
        background-color: #f2f2f2;
    }
    .affiliate_orders .custom-column {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
</style>
<div class="affiliate_orders">
<?php $orders = $block->getReport() ?>
<?php if ($orders):?>
    <h2>Orders:</h2>
        <table id='affiliate_orders_table'>
            <tr>
                <th>Order ID</th>
                <th>Increment ID</th>
                <th>Creation Date</th>
                <th>Total Amount</th>
            </tr>
    
    <?php foreach ($orders as $order):?>
            <tr>
                <td><?= $order['entity_id'] ?></td>
                <td><?= $order['increment_id']?></td>
                <td><?= $order['created_at']?></td>
                <td><?= $block->currencyFormatter($order['grand_total'])?></td>
            </tr>
            
    <?php endforeach;?>
    <tr>
                <td class="custom-column" colspan="4">New Row 1</td>
            </tr>

            <tr>
                <td class="custom-column" colspan="4">New Row 2</td>
            </tr>

            <tr>
                <td class="custom-column" colspan="4">New Row 3</td>
            </tr>
        </table>
<?php endif;?>
</div>
